#!/usr/bin/env bash

set -x

if [[ $UID != 0 ]]; then
    echo "Run as root!"
    exit 1
fi

if ! command -v tun2socks &>/dev/null; then
    echo "tun2socks executable is not in your PATH"
    exit 1
fi

CONFIG_PATH=$2
DEFAULT_INFO_PATH="/tmp/tun2socks-vpn-info"
IP_ROUTE_RULES_PATH="/tmp/ip-route-rules"
TUN_INTERFACE='tun0'

usage() {
    echo "Usage: vpn-mode.bash <run/kill> <vpn_config.bash>"
    exit 1
}

cleanup() {
    source "$DEFAULT_INFO_PATH"

    ip link set dev $TUN_INTERFACE down &>/dev/null
    ip route flush dev $TUN_INTERFACE &>/dev/null
    ip link del dev $TUN_INTERFACE &>/dev/null

    ip route flush dev $DEFAULT_INTERFACE &>/dev/null
    ip route flush table main &>/dev/null
    ip route restore < "$IP_ROUTE_RULES_PATH"

    if [[ -n "$SYSTEMD_RUN_UNIT" ]]; then
        systemctl kill "$SYSTEMD_RUN_UNIT"
    fi

    rm -f "$IP_ROUTE_RULES_PATH" "$DEFAULT_INFO_PATH"
}

run_tun2socks() {
    set -e
    source "$CONFIG_PATH" || usage

    local DEFAULT_INTERFACE=$(/sbin/ip route | awk '/default/' | grep -Eo 'dev.*' | cut -d ' ' -f2)
    local DEFAULT_GATEWAY=$(/sbin/ip route | awk '/default/' | grep -Eo 'via.*' | cut -d ' ' -f2)

    cat > "$DEFAULT_INFO_PATH" << EOF
DEFAULT_INTERFACE=$DEFAULT_INTERFACE
DEFAULT_GATEWAY=$DEFAULT_GATEWAY
EOF

    ip route save > "$IP_ROUTE_RULES_PATH"

    trap 'cleanup ; exit 1' ERR

    if ! ip link set dev $TUN_INTERFACE up &>/dev/null ; then
        ip tuntap add mode tun dev $TUN_INTERFACE
        ip addr add 198.18.0.1/15 dev $TUN_INTERFACE
        ip link set dev $TUN_INTERFACE up
    fi

    ip route del default
    ip route add default via 198.18.0.1 dev tun0

    ip route add "$CONFIG_EXTERNAL_SERVER_IP" via $DEFAULT_GATEWAY dev $DEFAULT_INTERFACE

    for i in "${CONFIG_EXCLUDE_CIDRS[@]}"; do
        ip route add "$i" via $DEFAULT_GATEWAY dev $DEFAULT_INTERFACE
    done

    local OUTPUT=$(systemd-run -p MemoryLimit=100M -p CPUQuota=20% --no-block -- \
        tun2socks -device $TUN_INTERFACE -proxy "$CONFIG_PROXY" --loglevel silent 2>&1 >/dev/null)

    cat >> "$DEFAULT_INFO_PATH" << EOF
SYSTEMD_RUN_UNIT=$(echo $OUTPUT | grep -Eo 'run-.*\.service')
EOF
}

if [[ "$1" == "kill" ]]; then
    cleanup || systemctl restart NetworkManager.service
elif [[ "$1" == "run" ]]; then
    run_tun2socks
else
    usage
fi
